require("config")
require("config.lazy")
require("plugins.lsp")

-- Keybind cheatsheet
vim.keymap.set('n', '<leader>?', function()
  local lines = {
    "╭─────────────────────── KEYBINDS ───────────────────────╮",
    "",
    "│ 📋 GENERAL                                          │",
    "│   <Space>  = Leader                                  │",
    "│   \\       = Local leader                            │",
    "",
    "│ 🔍 TELESCOPE (Normal)                               │",
    "│   <Space>ff  = Find files                            │",
    "│   <Space>fh  = Help tags                             │",
    "│   <Space>fs  = Grep string (search)                  │",
    "│   <Space>fv  = Find files in ~/.config/nvim           │",
    "│   <Space>fn  = Find files in ~/nix                   │",
    "│   <Space>fo  = Format buffer (LSP)                   │",
    "",
    "│ ⚓ HARPOON (Normal)                                  │",
    "│   <Space>a  = Add file                               │",
    "│   <Space>l  = Open Harpoon list                      │",
    "│   <Space>p  = Previous Harpoon buffer                 │",
    "│   <Space>n  = Next Harpoon buffer                     │",
    "",
    "│ 💻 LSP (Normal - on attach)                         │",
    "│   K        = Hover                                    │",
    "│   gd       = Go to definition                         │",
    "│   gD       = Go to declaration                        │",
    "│   gi       = Go to implementation                      │",
    "│   go       = Go to type definition                    │",
    "│   gr       = References                               │",
    "│   gs       = Signature help                           │",
    "│   <F2>     = Rename                                  │",
    "│   <F3>     = Format                                  │",
    "│   <F4>     = Code action                              │",
    "",
    "│ ⚡ nvim-cmp (Insert)                                 │",
    "│   <CR>     = Confirm                                 │",
    "│   <Tab>    = Next item / jump snippet                 │",
    "│   <S-Tab>  = Previous item / jump back               │",
    "│   <C-Space>= Show completion menu                    │",
    "│   <C-e>    = Abort                                   │",
    "│   <C-b>    = Scroll docs up                          │",
    "│   <C-f>    = Scroll docs down                        │",
    "",
    "│ 🤖 MINUET (Insert - VirtualText)                    │",
    "│   <A-A>    = Accept whole completion                 │",
    "│   <A-a>    = Accept one line                          │",
    "│   <A-z>    = Accept N lines                           │",
    "│   <A-]>    = Next completion / trigger                │",
    "│   <A-[>   = Previous completion                       │",
    "│   <A-e>    = Dismiss                                 │",
    "",
    "│ 🔀 GIT (Normal)                                      │",
    "│   <Space>gs = Git status                              │",
    "",
    "│ ⏪ UNDOTREE (Normal)                                 │",
    "│   <Space>u  = Toggle UndoTree                         │",
    "",
    "│ 📝 EDITING (Normal)                                  │",
    "│   <Space>ex = Open netrw (Ex)                        │",
    "│   Y        = Yank to end of line                      │",
    "│   <Space>y = Yank to clipboard (+)                    │",
    "│   <Space>Y = Yank line to clipboard (+)               │",
    "│   <Space>d = Delete to blackhole (_)                  │",
    "│   <Space>s = Replace word under cursor (global)       │",
    "│   <Space>x = Chmod +x (make executable)               │",
    "",
    "│ 📋 EDITING (Visual)                                  │",
    "│   J        = Move line down (with indent)             │",
    "│   K        = Move line up (with indent)               │",
    "│   <Space>p = Paste without yank (_)                   │",
    "│   <Space>y = Yank to clipboard (+)                    │",
    "│   <Space>d = Delete to blackhole (_)                  │",
    "",
    "│ ⌨️  NAVIGATION (Normal)                             │",
    "│   J        = Join with next line (keep cursor)        │",
    "│   n        = Next match + center + zv                 │",
    "│   N        = Previous match + center + zv             │",
    "│   <C-d>    = Scroll down + center                     │",
    "│   <C-u>    = Scroll up + center                       │",
    "│   <C-f>    = Open tmux sessionizer                    │",
    "",
    "│ 🐛 QUICKFIX/LOCATION LIST (Normal)                   │",
    "│   <C-k>    = Next quickfix item + center              │",
    "│   <C-j>    = Previous quickfix item + center          │",
    "│   <Space>k = Next location item + center              │",
    "│   <Space>j = Previous location item + center          │",
    "╰───────────────────────────────────────────────────────╯"
  }
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.api.nvim_set_current_buf(buf)
  vim.bo.filetype = 'markdown'
  vim.bo.modifiable = false
end, { desc = 'Open keybind cheatsheet' })
